# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTbcGj8kVJt-8KXmV-RJLV07weWWG7xt
"""

from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/warm_transfer', methods=['POST'])
def warm_transfer():
    data = request.json  # Get JSON data from Retell AI

    # Extract parameters
    caller_name = data.get("caller_name")
    debt_amount = data.get("debt_amount")
    summary = data.get("summary")

    print(f"Initiating warm transfer for {caller_name} with debt ${debt_amount}.")

    # Simulate transfer process
    transfer_status = {
        "success": True,
        "message": f"Call transferred successfully for {caller_name}."
    }

    return jsonify(transfer_status)  # Return JSON response to Retell AI

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)

